### ISSUE TITLE
Should I apply `normvar` or work on the output of `lcpm` for KNN / UMAP visualization?

### ISSUE THREAD

**Issue by const-ae** [lingfeiwang/normalisr#1]
Hi Lingfei Wang,

I would like to try out `normalisr` for visualization and KNN graph construction. I was wondering if you would recommend applying `normvar` function before or if it is better to run on the KNN graph construction on the output of `lcpm`?

The reason that I am asking is that if look at the mean-variance plot for both outputs, I was surprised to see that the variance of highly expressed genes is lower after callng `normvar` (purple dots) than before (green dots):

![image](https://user-images.githubusercontent.com/5359014/167601101-e7fef1cb-4bd0-44dd-85fe-2304c7b376d0.png)

Best,
Contantin

**Comment by lingfeiwang** [comment]
Hi Contantin,

Thank you for your interest in normalisr.

Normalisr was developed primarily for frequentist hypothesis testing such as differential expression and co-expression. Utility in dimensionality reduction was only briefly touched but I am looking forward to wider applications or more comprehensive benchmarking of normalisr.

Briefly, the `normvar` step was to remove potential heteroskedasticity due to technical confounders when looking at one gene across cells. One evidence for heteroskedasticity is the widespread underestimation of variance of log expression at low expression levels across different methods (Fig 3b in paper).

The figure you showed is in fact the expected outcome. Generally speaking, for Poisson or similar distributions, when the sampled value is $N$, its absolute deviation from expectation is $\delta N=N-E(N)\sim\sqrt N$. Therefore it should go higher with more reads. However normalisr computes the MMSE estimator for **log** expression. The absolute deviation of log expression is approximately the relative deviation of expression, i.e. $\delta(log N)\approx\delta N/N\sim N^{-1/2}$. Therefore we should see a decline as you showed.

Specifically, Fig 4 uses the final output of normalisr, after `normvar` and covariate removal. You can find the details in Methods.

Hope that answers your question. If not, let me know.

Best,
Lingfei

**Comment by const-ae** [comment]
Hi Lingfei,

thanks for the comprehensive response. This is very helpful :)

Best,
Constantin
